config/routes.rb
Rails.application.routes.draw do

  resources :students
  get 'cookies_management/set_encrypted_cookie'
  get 'cookies_management/read_encrypted_cookie'
  get 'cookies_management/destroy_encrypted_cookie'

  get 'cookies_management/create_cookie'
  get 'cookies_management/destroy_cookie'
  get 'cookies_management/show_cookie'

  get 'session_management/new_flash'
  get 'session_management/show_flash'
  get 'session_management/next_request'

  get 'session_management/index'
  get 'session_management/destroy'
  get 'session_management/show'

  get 'params/index'
  get 'params/new'
  post 'params/create'


  get 'cookies_management/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord

  def to_s
    "stdent #{self.name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cookies_management_controller.rb
class CookiesManagementController < ApplicationController
  def index
  end

  # http://localhost:3000/cookies_management/show_cookie

  def create_cookie
    cookies[:user_id] = "Nouman this is a cookie"
  end

  def destroy_cookie
    cookies.delete(:user_id)
  end

  def show_cookie
  end

  # ********************

  def set_encrypted_cookie
    cookies.encrypted[:expiration_date] = Date.tomorrow # => Thu, 20 Mar 2014
    redirect_to action: 'read_encrypted_cookie'
  end

  def read_encrypted_cookie
    # cookies.encrypted[:expiration_date] # => "2014-03-20"
  end

  def destroy_encrypted_cookie
    cookies.delete(:expiration_date)
  end
end

app/controllers/params_controller.rb
class ParamsController < ApplicationController

  # http://localhost:3000/params/new
  def new
  end

  def create
    puts "params:"
    p params
    p params[:id]
    p params[:client]
    p params[:client][:name]
    p params[:controller]
    p params[:action]

    # Permitted Scalar Values
    puts "before"
    p params.permit(:id )
    p params.permit(client: {} )
    p params.require(:client).permit!
    puts "after"
  end

  def index
  end

  def get_params

  end
end

# <ActionController::Parameters
# {
#   "authenticity_token"=>"V/EdwugpjvXEUCdb7Xe/9fr8ZsFuWy1Muot8TUV2QeaQlog5iqXWD96SOrA631bHAA88TPjfNcZ5hM5Oi7hqqQ==",
#   "id"=>"23",
#   "client"=>{"name"=>"Acme", "phone"=>"12345", "address"=>{"postcode"=>"12345", "city"=>"Carrot City"}},
#   "controller"=>"params",
#   "action"=>"create"
# }

# permitted: false>

app/controllers/session_management_controller.rb
class SessionManagementController < ApplicationController

  # Sessions
  # http://localhost:3000/session_management/index
  # http://localhost:3000/session_management/show
  # http://localhost:3000/session_management/destroy

  def index
    # To store something in the session, just assign it to the key like a hash:
    session[:current_user_id] = "Nouman"
  end

  def destroy
    # delete session
    session[:current_user_id] = nil
  end

  def show
    # show session
    @session_data= session[:current_user_id]
  end

  # ************************************
  # Flash

  # run in this order to understand
  # http://localhost:3000/session_management/new_flash
  # http://localhost:3000/session_management/show_flash
  # http://localhost:3000/session_management/next_request

  def new_flash
    flash[:notice] = "You have successfully logged out."
    flash[:hey] = "Hey this is a flash"
    # redirect_to session_management_show_flash_path
  end

  def show_flash
  end

  def next_requestSessionManagementController
  end

  # ******************************




end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update destroy ]
  after_action :show_message
  around_action :show_message_around
  # GET /students or /students.json
  def index
    @students = Student.all
  end

  # GET /students/1 or /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Student was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      puts "set student called"
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name)
    end

    def testing
      puts "testing"
    end

    def show_message
      puts self.testing   #  calling StudentsController method
      puts @student.to_s
      puts "after filter running"
    end

    def show_message_around
      # puts "show_message_around"
      begin
        puts "From around_action before yielding"
        # yield
        puts "From around_action after yielding"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cookies_management_helper.rb
module CookiesManagementHelper
end

app/helpers/params_helper.rb
module ParamsHelper
end

app/helpers/session_management_helper.rb
module SessionManagementHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/cookies_management/index.html.erb
<h1>CookiesManagement#index</h1>
<p>Find me in app/views/cookies_management/index.html.erb</p>

app/views/cookies_management/read_encrypted_cookie.html.erb
<h1>

  <%= cookies.encrypted[:expiration_date] %>
</h1>

app/views/cookies_management/show_cookie.html.erb
<h1>
<%= cookies[:user_id] %>

</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActionControllerBasics</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/params/index.html.erb
<h1>Params#index</h1>
<p>Find me in app/views/params/index.html.erb</p>

app/views/params/new.html.erb
<form accept-charset="UTF-8" action="/params/create"   method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="id" value="23" />
  <input type="text" name="client[name]" value="Acme" />
  <input type="text" name="client[phone]" value="12345" />
  <input type="text" name="client[address][postcode]" value="12345" />
  <input type="text" name="client[address][city]" value="Carrot City" />
  <input type="submit" value="Submit">
</form>

app/views/session_management/destroy.html.erb
<h1>session Destroyed</h1>
                              

app/views/session_management/index.html.erb
<h1>session created</h1>

app/views/session_management/next_request.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

app/views/session_management/show.html.erb
<h1><%=   @session_data  %></h1>

app/views/session_management/show_flash.html.erb
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>